apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:
      - name: init-mysql
        image: mysql:5.6
        command:
        - bash
        - "-c"
        - |
          set -ex                    
          # Copy appropriate conf.d files from config-map to emptyDir.          
          cp /mnt/config-map/my.cnf /etc/mysql/conf.d/
        volumeMounts:
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: config-map
          mountPath: /mnt/config-map
      containers:
      - image: mysql:5.6
        name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql
                key: mysql-root-password
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: data
            mountPath: /var/lib/mysql
          - name: conf
            mountPath: /etc/mysql/conf.d
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql
      - name: conf
        persistentVolumeClaim:
          claimName: mysql-conf
      - name: config-map
        configMap:
          name: mysql-config
